### ISSUE TITLE
How did you get the encryption key in exef2paz.cpp?

### ISSUE THREAD

**Issue by ghost** [Ouroboros/Ouroboros.github.io#1]
It will be kind for you to tell me that. I am dealing with some other paz files and eager to know the encryption key.

Thanks a lot.

**Comment by Ouroboros** [comment]
Hi, this source is directly taken from asmodean, I didn't modified anything
plz ask him for More info

http://asmodean.reverse.net/

**Comment by ghost** [comment]
Thanks a lot!
